apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-app-of-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    repoURL: https://github.com/Romiko/rancher-argocd-sandbox.git
    path: environments/dev
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
